name: firebase
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  get: 4.6.6
  flutter:
    sdk: flutter
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  firebase_messaging: ^14.7.5
  firebase_analytics: ^10.7.1
  flutter_local_notifications: ^16.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
