// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALrdQCxEgbaXQZKFy2t47cpSikhMGYaN4',
    appId: '1:713446987720:web:562b0a3eb74343a2e452fd',
    messagingSenderId: '713446987720',
    projectId: 'praktikum4firebase311',
    authDomain: 'praktikum4firebase311.firebaseapp.com',
    storageBucket: 'praktikum4firebase311.appspot.com',
    measurementId: 'G-70STV23NFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmW8P0WptV2kYkOLATSWQIy7Ep-HnOIiA',
    appId: '1:713446987720:android:2ecb13779af7e092e452fd',
    messagingSenderId: '713446987720',
    projectId: 'praktikum4firebase311',
    storageBucket: 'praktikum4firebase311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5N4QhnZgy-HZGYKOJssA7EuBp-1Yj730',
    appId: '1:713446987720:ios:733eb46f8db52152e452fd',
    messagingSenderId: '713446987720',
    projectId: 'praktikum4firebase311',
    storageBucket: 'praktikum4firebase311.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5N4QhnZgy-HZGYKOJssA7EuBp-1Yj730',
    appId: '1:713446987720:ios:e3bfd7f964b71609e452fd',
    messagingSenderId: '713446987720',
    projectId: 'praktikum4firebase311',
    storageBucket: 'praktikum4firebase311.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
